package org.example.bean.tests;

public enum MixedTests {
    VERIFY_ENDPOINT_WITH_FIELD_AS_EMPTY,
    VERIFY_ENDPOINT_WITH_FIELD_AS_SPECIAL_CHARACTER,
    VERIFY_ENDPOINT_WITH_FIELD_AS_RANDOM_NUMBERS,
    VERIFY_ENDPOINT_WITH_FIELD_GREATER_THAN_LENGTH,
    VERIFY_ENDPOINT_WITH_FIELD_LESS_THAN_LENGTH,
}
