package com.chocotea.bean.tests;

public enum NegativeTests {
    VERIFY_ENDPOINT_ERROR_WITH_INCORRECT_URL,
    VERIFY_ENDPOINT_ERROR_MESSAGE_WITH_EMPTY_FIELDS,
    VERIFY_ENDPOINT_ERROR_WITH_EMPTY_FIELDS
}
