
package org.example.core.annotations;

import java.lang.annotation.*;

@Target(ElementType.TYPE)
//TODO: reconfirm the policy here
@Retention(RetentionPolicy.SOURCE)
@Inherited
public @interface JavaxCollection {

    String name() default "Sample Collection";
    String receiveUrl() default "Autogenerated url";

//    AccessLevel value() default AccessLevel.PUBLIC;

    AnyAnnotation[] onMethod() default {};

    AnyAnnotation[] onParam() default {};


    @Deprecated
    @Retention(RetentionPolicy.SOURCE)
    @Target({})
    public @interface AnyAnnotation {
    }
}
